name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17', '21', '22', '23', '24', '25' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Check active Java version
        run: javac -version
      - name: Run tests
        run: mvn clean test
      - name: Run mutation tests
        run: mvn org.pitest:pitest-maven:mutationCoverage
